import './globals.css'
import {Manrope} from 'next/font/google'
import React from "react";
import Navbar from "@/components/navbar/Navbar";
import Panel from "../components/panel/SearchPanel";
import CreatePanel from "@/components/panel/CreatePanel";

const font = Manrope({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={font.className}>
        <Panel/>
        <CreatePanel/>
        <Navbar/>
        <main className="bg-col1 pb-20">{children}</main>
        </body>
        </html>
    )
}
